# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_LOCATION: 'eastus'
  AZURE_ENVIRONMENT: 'dev'  # your environment name here
  AZURE_SUBSCRIPTION_ID: '81e63c6d-7f3c-4e33-8a28-0036da979a43'

steps:
- task: UseDotNet@2
  inputs:
    version: '9.x'
    displayName: Set up .NET 9

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'acrserviceconnectionmanual'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install Azure Dev CLI (azd)
      curl -fsSL https://aka.ms/install-azd.sh | bash
      
      # Log in to Azure using the service connection (already handled)
      azd version
      azd config set auth.useAzCliAuth "true"
    
      pwd
      ls -la
      
      echo "Using environment: $(AZURE_ENVIRONMENT)"

      # Initialize azd project with environment
      azd init --environment $(AZURE_ENVIRONMENT)

      # Provision resources with environment
      azd provision --environment $(AZURE_ENVIRONMENT)

      # Deploy the application with environment
      azd deploy --environment $(AZURE_ENVIRONMENT)

    # env:
    #   AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    #   AZURE_LOCATION: $(AZURE_LOCATION)

  displayName: 'Run azd init, provision and deploy with environment'
